services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile

    ports:
      - "80:80"

    depends_on:
      - frontend
      - api

    networks:
      - ezyedutube-network

    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile

    expose:
      - "80"

    env_file:
      - ./client/.env.docker

    networks:
      - ezyedutube-network

    restart: always

  api:
    build:
      context: ./server
      dockerfile: Dockerfile

    expose:
      - "5000"

    env_file:
      - ./server/.env.docker

    environment:
      - DOCKER_ENV=true

    networks:
      - ezyedutube-network

    restart: always

networks:
  ezyedutube-network:
    driver: bridge