services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile

    ports:
      - "80:80"

    depends_on:
      - frontend
      - api

    networks:
      - ezyedutube-network

    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile

    expose:
      - "80"

    env_file:
      - ./client/.env.docker

    networks:
      - ezyedutube-network

    restart: always

  api:
    build:
      context: ./server
      dockerfile: Dockerfile

    expose:
      - "5000"

    env_file:
      - ./server/.env.docker.example

    environment:
      - DOCKER_ENV=true

    networks:
      - ezyedutube-network

    restart: always

  jenkins:
    # Official LTS image of Jenkins
    image: jenkins/jenkins:lts
    # container_name: ezyedutube-jenkins
    # Run as root to have permission to access host docker socket
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ezyedutube-network
    restart: always

networks:
  ezyedutube-network:
    driver: bridge

volumes:
  jenkins_data: